export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const SAVE_PAYMENT_MEDTHOD = "SAVE_PAYMENT_MEDTHOD";
export const CART_EMPTY = "CART_EMPTY";
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";
