const data = {
  products: [
    {
      _id: "1",
      name: "Champian Tshirt",
      category: "Shirts",
      image: "/images/product1.jpg",
      price: 130,
      countInStock: 5,
      brand: "Champian",
      rating: 2.5,
      numReviews: 10,
      description: "High Quarity product",
    },
    {
      _id: "2",
      name: "Test2 shirt",
      category: "Shirts",
      image: "/images/product2.jpg",
      countInStock: 1,
      price: 120,
      brand: "Champian",
      rating: 3.0,
      numReviews: 50,
      description: "High Quarity product",
    },
    {
      _id: "3",
      name: "Test3 shirt",
      category: "Shirts",
      image: "/images/product3.jpg",
      countInStock: 2,
      price: 160,
      brand: "Champian",
      rating: 2.0,
      numReviews: 40,
      description: "High Quarity product",
    },
    {
      _id: "4",
      name: "Test4 Tshirt",
      category: "Shirts",
      image: "/images/product4.jpg",
      countInStock: 3,
      price: 120,
      brand: "Champian",
      rating: 4.0,
      numReviews: 10,
      description: "High Quarity product",
    },
    {
      _id: "5",
      name: "Test5 shirt",
      category: "Shirts",
      image: "/images/product5.jpg",
      countInStock: 0,
      price: 120,
      brand: "Champian",
      rating: 3.5,
      numReviews: 10,
      description: "High Quarity product",
    },
    {
      _id: "6",
      name: "Test6 shirt",
      category: "Shirts",
      image: "/images/product6.jpg",
      countInStock: 5,
      price: 99,
      brand: "Champian",
      rating: 4.5,
      numReviews: 5,
      description: "High Quarity product",
    },
  ],
};

export default data;
